# This is the app name which is going to be displayed on main page and title
app_title: "Est ce que c'est bientôt l'heure du café ?"

# If no message is set, this one will be displayed
defaultMessage: "Non ce n'est pas l'heure."

# Optional
extraMessage: "         {\n      {   }\n       }_{ __{\n    .-{   }   }-.\n   (   }     {   )\n   |`-.._____..-'|\n   |             ;--.\n   |            (__  \\\n   |             | )  )\n   |             |/  /\n   |             /  /\n   |            (  /\n   \\             y'\n    `-.._____..-'\n"

# List of defined messages
messages:
  - message: "Va te coucher plutôt."
    startTime: 0:00
    endTime: 7:30

  - message: "Si tu es déjà au boulot, tu mérites bien un café."
    startTime: 7:30
    endTime: 8:50
    itsTime: True

  - message: "A voir."
    startTime: 8:50
    endTime: 9:20

  - message: "C'est plutot l'heure du scrum meeting."
    startTime: 9:20
    endTime: 9:30

  - message: "Non c'est pas l'heure."
    startTime: 9:30
    endTime: 10:10

  - message: "Presque."
    startTime: 10:10
    endTime: 10:20

  - message: "Oui, enfin."
    startTime: 10:20
    endTime: 10:40
    itsTime: True

  - message: "Après l'heure c'est plus l'heure."
    startTime: 10:40
    endTime: 11:30

  - message: "Non mais on va bientôt manger."
    startTime: 11:30
    endTime: 12:00

  - message: "A table !"
    startTime: 12:00
    endTime: 13:00

  - message: "Pourquoi pas."
    startTime: 13:00
    endTime: 13:30

  - message: "Oui, enfin."
    startTime: 15:20
    endHour: 15:40
    endTime: True

  - message: "Non, c'est l'heure de bosser."
    startTime: 15:40
    endTime: 17:30

  - message: "Non, mais la journée est presque finie."
    startTime: 17:30
    endTime: 18:00

  - message: "C'est l'heure de rentrer."
    startTime: 18:00
    endTime: 23:59
